template_project/basic/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
#template tagging 
app_name = 'basic'

urlpatterns = [
	url(r'relative/$',views.relative,name='relative'),
	url(r'other/$',views.other,name='other'),
]

template_project/template_project/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from basic import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    path('basic/',include('basic.urls'))
]

template_project/basic/models.py
from django.db import models

# Create your models here.

template_project/basic/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	data = {'data':'hello world'}
	return render(request,'basic/index.html',{'data':'hello world'})

def other(request):
	return render(request,'basic/other.html')

def relative(request):
	return render(request,'basic/relative_url_template.html')

template_project/templates/basic/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a  class="navbar-brand" href="{% url 'index' %}">BRAND</a>
				<li><a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
				<li><a class="nav-item nav-link" href="{% url 'basic:other'%}">Other</a></li>
			</ul>
		</div>
	</nav>
	<div class="container">
		{% block body_block %}
		<!-- anything outside this will be inherited -->
		{% endblock %}
	</div>
</body>
</html>

template_project/templates/basic/index.html
<!DOCTYPE html>
{% extends "basic/base.html" %}
{% block body_block %}
	<h1>Welcome to INDEX</h1>
	<h2>THIS is ondec </h2>
	<h1>{{data|cut:'world'}}</h1>
{% endblock %}
<h2>THIS is ondec </h2>

template_project/templates/basic/other.html
<!DOCTYPE html>
{% extends "basic/base.html" %}
{% block body_block %}
	<h1>Welcome to others</h1>
{% endblock %}

template_project/templates/basic/relative_url_template.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Welcome to relative</h1>
	<a href="{% url 'basic:other' %}">Other page</a>
	<a href="{% url 'admin:index' %}">admin</a>
	<a href="{% url 'index' %}">Index</a>
</body>
</html>